# Generated by Django 6.0.1 on 2026-01-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='robe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.robe'),
        ),
    ]
